name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      # 请求手动激活文件
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.62f1   # 请确认与你的项目版本一致
      # 上传生成的 .alf 文件作为 Artifact (使用 v4)
      - name: Expose as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityActivationFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
